name: typo-typer

services:
  postgres:
    container_name: postgres
    image: postgres:18.3-alpine
    volumes:
      - postgres:/var/lib/postgresql
    environment:
      POSTGRES_DB: typo-typer
      PGDATABASE: typo-typer
      POSTGRES_USER: admin
      PGUSER: admin
      POSTGRES_PASSWORD: adminpassword
      PGPASSWORD: adminpassword
    ports:
      - "5433:5432"
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d typo-typer" ]
      interval: 5s
      timeout: 10s
      retries: 5

volumes:
  postgres:
