name: typo-typer

services:
  postgres:
    container_name: postgres
    build:
      context: ./docker/postgres/
      dockerfile: initialize.dockerfile
    volumes:
      - postgres:/data/postgres
    env_file: ./.env
    environment:
      PGUSER: ${POSTGRES_USER}
      PGPASSWORD: ${POSTGRES_PASSWORD}
      PGDATABASE: ${POSTGRES_DB}
      PGDATA: /var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"
    networks:
      - db
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 10s
      retries: 5

networks:
  db:
    driver: bridge

volumes:
  postgres:
